version: 2.19.0.{build}
image: Visual Studio 2017
install:
  - set QTDIR=C:\Qt\5.12.5\msvc2017_64
  - set MSVC_DIR=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build
  - set PATH=%PATH%;%QTDIR%\bin;%MSVC_DIR%
  - set ARCHITECTURE=x86_amd64
build_script:
  - call vcvarsall.bat %ARCHITECTURE%
  - dir
  - mkdir build
  - cd build
  - qmake ../BuildDltViewer.pro
  - nmake
test: off
