#ifndef GLOBALS_H
#define GLOBALS_H

#define COLUMN_CHECK 4
#define COLUMN_APID 0
#define COLUMN_CTID 0
#define COLUMN_FILEID 0
#define COLUMN_FILENAME 1
#define COLUMN_FILEDATE 2
#define COLUMN_STATUS 3
#define COLUMN_SIZE 5
#define COLUMN_PACKAGES 6
#define COLUMN_RECPACKAGES 7
#define COLUMN_BUFFERSIZE 8

#define PROTOCOL_FLST_SFLAG 0
#define PROTOCOL_FLST_FILEID 1
#define PROTOCOL_FLST_FILENAME 2
#define PROTOCOL_FLST_FILEDATE 4
#define PROTOCOL_FLST_SIZE 3
#define PROTOCOL_FLST_PACKAGES 5
#define PROTOCOL_FLST_BUFFERSIZE 6
#define PROTOCOL_FLST_EFLAG 7

#define PROTOCOL_FLDA_SFLAG 0
#define PROTOCOL_FLDA_FILEID 1
#define PROTOCOL_FLDA_PACKAGENR 2
#define PROTOCOL_FLDA_DATA 3
#define PROTOCOL_FLDA_EFLAG 4

#define PROTOCOL_FLFI_SLFAG 0
#define PROTOCOL_FLFI_FILEID 1
#define PROTOCOL_FLFI_EFLAG 2

#define PROTOCOL_FLER_SFLAG 0
#define PROTOCOL_FLER_ERRCODE1 1
#define PROTOCOL_FLER_ERRCODE2 2
#define PROTOCOL_FLER_FILENAME 3
#define PROTOCOL_FLER_EFLAG 4

#define PROTOCOL_FLIF_SFLAG 0
#define PROTOCOL_FLIF_EFLAG 11

#define PROTOCOL_ALL_SFLAG 0

#endif // GLOBALS_H
