#ifndef INDEXTHREADWORKER_H
#define INDEXTHREADWORKER_H

#include "qdltfilterlist.h"

#include <QByteArray>
#include <QMutex>
#include <QQueue>
#include <QThread>
#include <QVector>
#include <QWaitCondition>

class QDltPluginManager;

/**
 * @brief Per-file input metadata for incremental indexing.
 */
struct IndexThreadFileInput
{
    int fileIndex{-1};
    int baseGlobalIndex{0};
    int existingMessageCount{0};
    QString fileName;
    qint64 lastIndexedPosition{-1};
};

/**
 * @brief Runtime options used while processing an index batch.
 */
struct IndexThreadBatchContext
{
    QDltFilterList filterList;
    bool filtersEnabled{false};
    bool pluginsEnabled{false};
    bool silentMode{true};
    bool dltv2Support{false};
};

/**
 * @brief Per-message output produced by index batch processing.
 */
struct IndexThreadBatchResultItem
{
    int index{-1};
    bool passFilter{false};
    bool valid{false};
    QDltMsg undecodedMsg;
    QDltMsg decodedMsg;
};

/**
 * @brief Per-file indexing update generated by worker processing.
 */
struct IndexThreadFileResult
{
    int fileIndex{-1};
    QVector<qint64> newPositions;
};

/**
 * @brief Aggregated output for one processed indexing batch.
 */
struct IndexThreadBatchResult
{
    bool pluginsEnabled{false};
    QVector<IndexThreadFileResult> fileUpdates;
    QVector<IndexThreadBatchResultItem> items;
    QVector<qint64> matchingIndices;
};

Q_DECLARE_METATYPE(IndexThreadBatchResult)

/**
 * @brief Background worker that scans appended file regions and evaluates filters.
 */
class IndexThreadWorker : public QThread
{
    Q_OBJECT

public:
    /**
     * @brief Constructs the indexing worker.
     * @param pluginManager Plugin manager used for optional decoding.
     * @param parent QObject parent.
     */
    explicit IndexThreadWorker(QDltPluginManager *pluginManager, QObject *parent = nullptr);

    /**
     * @brief Stops and destroys the worker thread.
     */
    ~IndexThreadWorker() override;

    /**
     * @brief Enqueues a batch of files for incremental processing.
     * @param files File inputs moved into the worker queue.
     * @param context Batch options snapshot.
     */
    void enqueueBatch(QVector<IndexThreadFileInput> &&files,
                      const IndexThreadBatchContext &context);

    /**
     * @brief Requests worker termination.
     */
    void stopWorker();

signals:
    /**
     * @brief Emitted when one queued batch has been processed.
     * @param result Processed batch output.
     */
    void batchProcessed(const IndexThreadBatchResult &result);

protected:
    void run() override;

private:
    struct PendingBatch
    {
        QVector<IndexThreadFileInput> files;
        IndexThreadBatchContext context;
    };

    static IndexThreadBatchResult processBatch(const PendingBatch &batch,
                                               QDltPluginManager *pluginManager);

    QMutex m_queueMutex;
    QWaitCondition m_waitCondition;
    QQueue<PendingBatch> m_pendingBatches;
    bool m_stopRequested{false};
    QDltPluginManager *m_pluginManager{nullptr};
};

#endif // INDEXTHREADWORKER_H
