#ifndef __VERSION_H_
#define __VERSION_H_

#define PACKAGE_VERSION_STATE "BETA"
#define PACKAGE_MAJOR_VERSION "2"
#define PACKAGE_MINOR_VERSION "5"
#define PACKAGE_PATCH_LEVEL "0"
#define PACKAGE_VERSION "2.5.0_BETA"
#define PACKAGE_REVISION ""
#endif
